# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  latex_compilation:
    name: LaTeX compilation
    runs-on: ubuntu-latest
    steps:
    - uses: dante-ev/latex-action@v0.2.0
      with:
          root_file: ./tesis.tex
